/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xts_aes;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author humam
 */
public class Encrypt extends javax.swing.JPanel {

    /**
     * Creates new form Encrypt
     */
    
    public Encrypt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public static void main(String args[]) {
        System.out.println("hahah");
        String sourceField, keyField, targetField;
        String sourceName, keyName, targetName;
        sourceField = "D:/LMS/mik/cis/tugas/XTS_AES/src/xts_aes/cobaMatrix.py";
        keyField = "D:/LMS/mik/cis/tugas/XTS_AES/src/xts_aes/key.txt";
        targetField = "D:/LMS/mik/cis/tugas/XTS_AES/src/xts_aes/cobaMatrixDecrypt.py";
        sourceName = sourceField;
        keyName = keyField;
        targetName = targetField;
        XTS_AES aes = new XTS_AES(sourceName, keyName, targetName);
        try {
            aes.startEncryption(sourceName, keyName, targetName);
        }catch(Exception ex) {
            Logger.getLogger(Encrypt.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
